general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

# BACKLIGHTS
listener {
    timeout = 150
    on-timeout = playerctl -a status 2>/dev/null | grep -q "Playing" || (brightnessctl -s set 1 && brightnessctl -sd platform::kbd_backlight set 0)
    on-resume = ( [ $(brightnessctl get) -eq 1 ] && brightnessctl -r ) ; ( [ $(brightnessctl -d platform::kbd_backlight get) -eq 0 ] && brightnessctl -rd platform::kbd_backlight )
}

# LOCK
listener {
    timeout = 300
    on-timeout = playerctl -a status 2>/dev/null | grep -q "Playing" || loginctl lock-session
}

# DIM SCREEN / DPMS
listener {
    timeout = 450
    on-timeout = playerctl -a status 2>/dev/null | grep -q "Playing" || hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# SLEEP
listener {
    timeout = 600 # 10 min
    on-timeout = playerctl -a status 2>/dev/null | grep -q "Playing" || systemctl suspend-then-hibernate
}
